In [1]:
import numpy as np
import pickle
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import cv2
import os


In [2]:
def load_images_from_folder(folder, label):
    images = []
    labels = []
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder, filename))
        if img is not None:
            img = cv2.resize(img, (224, 224))  # Resize images to 224x224 pixels
            images.append(img)
            labels.append(label)
    return images, labels

real_images, real_labels = load_images_from_folder('dataset/real', 0)
fake_images, fake_labels = load_images_from_folder('dataset/fake', 1)

# Combine real and fake data
images = np.array(real_images + fake_images)
labels = np.array(real_labels + fake_labels)


In [31]:
print(images)

[[[[ 80 174 189]
   [ 78 175 189]
   [ 80 175 192]
   ...
   [154 170 217]
   [145 160 216]
   [135 151 210]]

  [[ 78 176 190]
   [ 87 187 202]
   [ 94 193 209]
   ...
   [139 152 207]
   [130 141 201]
   [125 137 198]]

  [[ 95 196 211]
   [ 96 200 214]
   [ 98 200 218]
   ...
   [129 141 199]
   [120 130 190]
   [132 143 201]]

  ...

  [[122  86 106]
   [119  87 104]
   [120  94 108]
   ...
   [ 29  17  23]
   [ 32  22  25]
   [ 37  30  31]]

  [[113  80 101]
   [123  93 112]
   [130 103 119]
   ...
   [ 28  14  18]
   [ 33  22  25]
   [ 31  23  24]]

  [[109  80 103]
   [115  87 107]
   [124  96 115]
   ...
   [ 31  18  20]
   [ 30  18  20]
   [ 32  22  25]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255

In [4]:
x_train, x_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)
x_train = x_train / 255.0  # Normalize pixel values
x_test = x_test / 255.0


In [5]:
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


c:\Users\Ajay\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))



Epoch 1/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 59s 1s/step - accuracy: 0.5460 - loss: 1.5159 - val_accuracy: 0.5330 - val_loss: 0.7050
Epoch 2/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 57s 1s/step - accuracy: 0.5647 - loss: 0.6913 - val_accuracy: 0.5795 - val_loss: 0.6757
Epoch 3/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 57s 1s/step - accuracy: 0.5964 - loss: 0.6642 - val_accuracy: 0.5990 - val_loss: 0.6592
Epoch 4/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 53s 1s/step - accuracy: 0.6214 - loss: 0.6650 - val_accuracy: 0.6284 - val_loss: 0.6367
Epoch 5/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 52s 1s/step - accuracy: 0.6828 - loss: 0.5963 - val_accuracy: 0.5868 - val_loss: 0.6828
Epoch 6/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 52s 1s/step - accuracy: 0.7375 - loss: 0.5159 - val_accuracy: 0.5575 - val_loss: 0.7729
Epoch 7/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 53s 1s/step - accuracy: 0.7782 - loss: 0.4430 - val_accuracy: 0.5428 - val_loss: 0.7921
Epoch 8/10
51/51 ━━━━━━━━━━━━━━━━━━━━ 57s 1s/step - accuracy: 0.8615 - loss: 0.3171 - val_accuracy: 0.5501 - val_loss:

In [7]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

13/13 ━━━━━━━━━━━━━━━━━━━━ 4s 346ms/step - accuracy: 0.4760 - loss: 2.0312
Test Accuracy: 52.57%


In [3]:
real_images, real_labels = load_images_from_folder('testdata/real', 0)
fake_images, fake_labels = load_images_from_folder('testdata/fake', 1)

In [4]:
images = np.array(real_images + fake_images)
labels = np.array(real_labels + fake_labels)
len(images)

2041

In [5]:
model.predict(images)

NameError: name 'model' is not defined

In [6]:
loss,accuracy = model.evaluate(images,labels)

NameError: name 'model' is not defined

In [8]:
with open('model.pickle','rb') as file:
    m = pickle.load(file)
loss,accuracy = m.evaluate(images,labels)

64/64 ━━━━━━━━━━━━━━━━━━━━ 12s 182ms/step - accuracy: 0.9067 - loss: 136.6563
